import "components/assets/fonts/Orbitron-Regular.ttf";

export global Theme {
    // primary
    out property <color> ot-dark-green: #002D2A;
    out property <color> ot-light-green: #22BC72;
    out property <color> ot-purple: #C1B7ED;
    out property <color> ot-gray: #D4D4D4;
    out property <color> ot-dark-gray: #2B2B2B;
    out property <color> ot-white:#F5F5F5;
    out property <color> black: #000000;

    out property <color> ot-light-green-alpha-50: rgba(34, 188, 114, 0.5);

    out property <string> font-family: "Orbitron";
}
