import { Theme } from "../theme.slint";
export global CourrierNotificationsAdpater {
    in property <string> message: "";
}

export component CourrierNotifications inherits Window {
    in property <string> message: CourrierNotificationsAdpater.message;

    width: 250px;
    height: 350px;

    Image {
        source: @image-url("assets/card.svg");
        height: 100%;
        width: 100%;
    }

    Image {
        source: @image-url("assets/left_widget/notifications.svg");
        x: parent.width - 100px;
        y: 50px;
        width: 40px;
        height: 40px;
    }

    VerticalLayout {
        alignment: center;
        padding: 50px;
        spacing: 10px;

        Text {
            text: message;
            wrap: word-wrap;
            letter-spacing: 1px;
            font-size: 15px;
            color: Theme.ot-white;
        }
    }
}
