export global TellTalesAdapter {
    in property <bool> fog: false;
    in property <bool> highbeam: false;
    in property <bool> bendbeam: false;
    in property <bool> park: false;
    in property <bool> brake: false;
    in property <bool> tire: false;
    in property <bool> left_signal: false;
    in property <bool> right_signal: false;
}

export component LightTellTales inherits Window {
    in property <bool> fog <=> TellTalesAdapter.fog;
    in property <bool> high-beam <=> TellTalesAdapter.highbeam;
    in property <bool> bend-beam <=> TellTalesAdapter.bendbeam;

    HorizontalLayout {
        padding: 20px;
        spacing: 10px;

        Image {
            source: @image-url("assets/telltales/fog.svg");
            visible: fog;
        }

        Image {
            source: @image-url("assets/telltales/high_beam.svg");
            visible: high-beam;
        }

        Image {
            source: @image-url("assets/telltales/bend_beam.svg");
            visible: bend-beam;
        }
    }
}

export component ControlTellTales inherits Window {
    in property <bool> park <=> TellTalesAdapter.park;
    in property <bool> brake <=> TellTalesAdapter.brake;
    in property <bool> tire <=> TellTalesAdapter.tire;

    HorizontalLayout {
        padding: 20px;
        spacing: 10px;

        Image {
            source: @image-url("assets/telltales/park.svg");
            visible: park;
        }

        Image {
            source: @image-url("assets/telltales/brake.svg");
            visible: brake;
        }

        Image {
            source: @image-url("assets/telltales/tire.svg");
            visible: tire;
        }
    }
}

export component LeftSignal inherits Window {
    in property <bool> left-signal <=> TellTalesAdapter.left_signal;

    Image {
        source: @image-url("assets/telltales/left_signal.svg");
        height: 50px;
        width: 50px;
        visible: left-signal;
    }
}

export component RightSignal inherits Window {
    in property <bool> right-signal <=> TellTalesAdapter.right_signal;

    Image {
        source: @image-url("assets/telltales/right_signal.svg");
        height: 50px;
        width: 50px;
        visible: right-signal;
    }
}
